[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback (React Router, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@huggingface/inference"]